// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/client/login.proto

package client

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type C2S_Login struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	AreaID               int32    `protobuf:"varint,2,opt,name=areaID,proto3" json:"areaID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2S_Login) Reset()         { *m = C2S_Login{} }
func (m *C2S_Login) String() string { return proto.CompactTextString(m) }
func (*C2S_Login) ProtoMessage()    {}
func (*C2S_Login) Descriptor() ([]byte, []int) {
	return fileDescriptor_6029277375332a30, []int{0}
}

func (m *C2S_Login) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2S_Login.Unmarshal(m, b)
}
func (m *C2S_Login) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2S_Login.Marshal(b, m, deterministic)
}
func (m *C2S_Login) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2S_Login.Merge(m, src)
}
func (m *C2S_Login) XXX_Size() int {
	return xxx_messageInfo_C2S_Login.Size(m)
}
func (m *C2S_Login) XXX_DiscardUnknown() {
	xxx_messageInfo_C2S_Login.DiscardUnknown(m)
}

var xxx_messageInfo_C2S_Login proto.InternalMessageInfo

func (m *C2S_Login) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *C2S_Login) GetAreaID() int32 {
	if m != nil {
		return m.AreaID
	}
	return 0
}

type S2C_Login struct {
	AccountId            uint64   `protobuf:"varint,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S2C_Login) Reset()         { *m = S2C_Login{} }
func (m *S2C_Login) String() string { return proto.CompactTextString(m) }
func (*S2C_Login) ProtoMessage()    {}
func (*S2C_Login) Descriptor() ([]byte, []int) {
	return fileDescriptor_6029277375332a30, []int{1}
}

func (m *S2C_Login) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2C_Login.Unmarshal(m, b)
}
func (m *S2C_Login) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2C_Login.Marshal(b, m, deterministic)
}
func (m *S2C_Login) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2C_Login.Merge(m, src)
}
func (m *S2C_Login) XXX_Size() int {
	return xxx_messageInfo_S2C_Login.Size(m)
}
func (m *S2C_Login) XXX_DiscardUnknown() {
	xxx_messageInfo_S2C_Login.DiscardUnknown(m)
}

var xxx_messageInfo_S2C_Login proto.InternalMessageInfo

func (m *S2C_Login) GetAccountId() uint64 {
	if m != nil {
		return m.AccountId
	}
	return 0
}

func init() {
	proto.RegisterType((*C2S_Login)(nil), "client.C2S_Login")
	proto.RegisterType((*S2C_Login)(nil), "client.S2C_Login")
}

func init() { proto.RegisterFile("proto/client/login.proto", fileDescriptor_6029277375332a30) }

var fileDescriptor_6029277375332a30 = []byte{
	// 130 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x28, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0xce, 0xc9, 0x4c, 0xcd, 0x2b, 0xd1, 0xcf, 0xc9, 0x4f, 0xcf, 0xcc, 0xd3, 0x03,
	0x0b, 0x09, 0xb1, 0x41, 0xc4, 0x94, 0x2c, 0xb9, 0x38, 0x9d, 0x8d, 0x82, 0xe3, 0x7d, 0x40, 0x52,
	0x42, 0x22, 0x5c, 0xac, 0x25, 0xf9, 0xd9, 0xa9, 0x79, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41,
	0x10, 0x8e, 0x90, 0x18, 0x17, 0x5b, 0x62, 0x51, 0x6a, 0xa2, 0xa7, 0x8b, 0x04, 0x93, 0x02, 0xa3,
	0x06, 0x6b, 0x10, 0x94, 0xa7, 0xa4, 0xc9, 0xc5, 0x19, 0x6c, 0xe4, 0x0c, 0xd5, 0x2a, 0xc3, 0xc5,
	0x99, 0x98, 0x9c, 0x9c, 0x5f, 0x9a, 0x57, 0xe2, 0x99, 0x02, 0xd6, 0xce, 0x12, 0x84, 0x10, 0x48,
	0x62, 0x03, 0x5b, 0x6a, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x1c, 0x4b, 0xfd, 0x0e, 0x90, 0x00,
	0x00, 0x00,
}
