// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/client/msg.proto

package client

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// ping包
// C2S_PING = 5;S2C_PING = 6;
type Ping struct {
	ClientSend           uint64   `protobuf:"fixed64,1,opt,name=client_send,json=clientSend,proto3" json:"client_send,omitempty"`
	GateRecv             uint64   `protobuf:"fixed64,2,opt,name=gate_recv,json=gateRecv,proto3" json:"gate_recv,omitempty"`
	GateSend             uint64   `protobuf:"fixed64,3,opt,name=gate_send,json=gateSend,proto3" json:"gate_send,omitempty"`
	GsRecv               uint64   `protobuf:"fixed64,4,opt,name=gs_recv,json=gsRecv,proto3" json:"gs_recv,omitempty"`
	GsSend               uint64   `protobuf:"fixed64,5,opt,name=gs_send,json=gsSend,proto3" json:"gs_send,omitempty"`
	GateBackRev          uint64   `protobuf:"fixed64,6,opt,name=gate_back_rev,json=gateBackRev,proto3" json:"gate_back_rev,omitempty"`
	GateBackSend         uint64   `protobuf:"fixed64,7,opt,name=gate_back_send,json=gateBackSend,proto3" json:"gate_back_send,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ping) Reset()         { *m = Ping{} }
func (m *Ping) String() string { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()    {}
func (*Ping) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7504516c9b8cbfc, []int{0}
}

func (m *Ping) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ping.Unmarshal(m, b)
}
func (m *Ping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ping.Marshal(b, m, deterministic)
}
func (m *Ping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ping.Merge(m, src)
}
func (m *Ping) XXX_Size() int {
	return xxx_messageInfo_Ping.Size(m)
}
func (m *Ping) XXX_DiscardUnknown() {
	xxx_messageInfo_Ping.DiscardUnknown(m)
}

var xxx_messageInfo_Ping proto.InternalMessageInfo

func (m *Ping) GetClientSend() uint64 {
	if m != nil {
		return m.ClientSend
	}
	return 0
}

func (m *Ping) GetGateRecv() uint64 {
	if m != nil {
		return m.GateRecv
	}
	return 0
}

func (m *Ping) GetGateSend() uint64 {
	if m != nil {
		return m.GateSend
	}
	return 0
}

func (m *Ping) GetGsRecv() uint64 {
	if m != nil {
		return m.GsRecv
	}
	return 0
}

func (m *Ping) GetGsSend() uint64 {
	if m != nil {
		return m.GsSend
	}
	return 0
}

func (m *Ping) GetGateBackRev() uint64 {
	if m != nil {
		return m.GateBackRev
	}
	return 0
}

func (m *Ping) GetGateBackSend() uint64 {
	if m != nil {
		return m.GateBackSend
	}
	return 0
}

type Test1 struct {
	A                    int32    `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	B                    string   `protobuf:"bytes,2,opt,name=b,proto3" json:"b,omitempty"`
	C                    []uint64 `protobuf:"fixed64,3,rep,packed,name=c,proto3" json:"c,omitempty"`
	ID                   int32    `protobuf:"varint,4,opt,name=ID,proto3" json:"ID,omitempty"`
	COUNT                int32    `protobuf:"varint,5,opt,name=COUNT,proto3" json:"COUNT,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Test1) Reset()         { *m = Test1{} }
func (m *Test1) String() string { return proto.CompactTextString(m) }
func (*Test1) ProtoMessage()    {}
func (*Test1) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7504516c9b8cbfc, []int{1}
}

func (m *Test1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Test1.Unmarshal(m, b)
}
func (m *Test1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Test1.Marshal(b, m, deterministic)
}
func (m *Test1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Test1.Merge(m, src)
}
func (m *Test1) XXX_Size() int {
	return xxx_messageInfo_Test1.Size(m)
}
func (m *Test1) XXX_DiscardUnknown() {
	xxx_messageInfo_Test1.DiscardUnknown(m)
}

var xxx_messageInfo_Test1 proto.InternalMessageInfo

func (m *Test1) GetA() int32 {
	if m != nil {
		return m.A
	}
	return 0
}

func (m *Test1) GetB() string {
	if m != nil {
		return m.B
	}
	return ""
}

func (m *Test1) GetC() []uint64 {
	if m != nil {
		return m.C
	}
	return nil
}

func (m *Test1) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Test1) GetCOUNT() int32 {
	if m != nil {
		return m.COUNT
	}
	return 0
}

type Test2 struct {
	A                    int64    `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	Xxxaa                []int32  `protobuf:"zigzag32,2,rep,packed,name=xxxaa,proto3" json:"xxxaa,omitempty"`
	Ccccxxxxxxxxx        int64    `protobuf:"varint,3,opt,name=ccccxxxxxxxxx,proto3" json:"ccccxxxxxxxxx,omitempty"`
	ID                   int32    `protobuf:"varint,4,opt,name=ID,proto3" json:"ID,omitempty"`
	COUNT                int32    `protobuf:"varint,5,opt,name=COUNT,proto3" json:"COUNT,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Test2) Reset()         { *m = Test2{} }
func (m *Test2) String() string { return proto.CompactTextString(m) }
func (*Test2) ProtoMessage()    {}
func (*Test2) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7504516c9b8cbfc, []int{2}
}

func (m *Test2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Test2.Unmarshal(m, b)
}
func (m *Test2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Test2.Marshal(b, m, deterministic)
}
func (m *Test2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Test2.Merge(m, src)
}
func (m *Test2) XXX_Size() int {
	return xxx_messageInfo_Test2.Size(m)
}
func (m *Test2) XXX_DiscardUnknown() {
	xxx_messageInfo_Test2.DiscardUnknown(m)
}

var xxx_messageInfo_Test2 proto.InternalMessageInfo

func (m *Test2) GetA() int64 {
	if m != nil {
		return m.A
	}
	return 0
}

func (m *Test2) GetXxxaa() []int32 {
	if m != nil {
		return m.Xxxaa
	}
	return nil
}

func (m *Test2) GetCcccxxxxxxxxx() int64 {
	if m != nil {
		return m.Ccccxxxxxxxxx
	}
	return 0
}

func (m *Test2) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Test2) GetCOUNT() int32 {
	if m != nil {
		return m.COUNT
	}
	return 0
}

type Test3 struct {
	Axxxxx               string   `protobuf:"bytes,1,opt,name=axxxxx,proto3" json:"axxxxx,omitempty"`
	Vxxxx                int32    `protobuf:"zigzag32,2,opt,name=vxxxx,proto3" json:"vxxxx,omitempty"`
	A                    int32    `protobuf:"varint,3,opt,name=a,proto3" json:"a,omitempty"`
	B                    int32    `protobuf:"varint,4,opt,name=b,proto3" json:"b,omitempty"`
	C                    int32    `protobuf:"varint,5,opt,name=c,proto3" json:"c,omitempty"`
	D                    int32    `protobuf:"varint,6,opt,name=d,proto3" json:"d,omitempty"`
	E                    int32    `protobuf:"varint,7,opt,name=e,proto3" json:"e,omitempty"`
	F                    string   `protobuf:"bytes,8,opt,name=f,proto3" json:"f,omitempty"`
	ID                   int32    `protobuf:"varint,9,opt,name=ID,proto3" json:"ID,omitempty"`
	COUNT                int32    `protobuf:"varint,10,opt,name=COUNT,proto3" json:"COUNT,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Test3) Reset()         { *m = Test3{} }
func (m *Test3) String() string { return proto.CompactTextString(m) }
func (*Test3) ProtoMessage()    {}
func (*Test3) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7504516c9b8cbfc, []int{3}
}

func (m *Test3) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Test3.Unmarshal(m, b)
}
func (m *Test3) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Test3.Marshal(b, m, deterministic)
}
func (m *Test3) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Test3.Merge(m, src)
}
func (m *Test3) XXX_Size() int {
	return xxx_messageInfo_Test3.Size(m)
}
func (m *Test3) XXX_DiscardUnknown() {
	xxx_messageInfo_Test3.DiscardUnknown(m)
}

var xxx_messageInfo_Test3 proto.InternalMessageInfo

func (m *Test3) GetAxxxxx() string {
	if m != nil {
		return m.Axxxxx
	}
	return ""
}

func (m *Test3) GetVxxxx() int32 {
	if m != nil {
		return m.Vxxxx
	}
	return 0
}

func (m *Test3) GetA() int32 {
	if m != nil {
		return m.A
	}
	return 0
}

func (m *Test3) GetB() int32 {
	if m != nil {
		return m.B
	}
	return 0
}

func (m *Test3) GetC() int32 {
	if m != nil {
		return m.C
	}
	return 0
}

func (m *Test3) GetD() int32 {
	if m != nil {
		return m.D
	}
	return 0
}

func (m *Test3) GetE() int32 {
	if m != nil {
		return m.E
	}
	return 0
}

func (m *Test3) GetF() string {
	if m != nil {
		return m.F
	}
	return ""
}

func (m *Test3) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Test3) GetCOUNT() int32 {
	if m != nil {
		return m.COUNT
	}
	return 0
}

func init() {
	proto.RegisterType((*Ping)(nil), "client.Ping")
	proto.RegisterType((*Test1)(nil), "client.Test1")
	proto.RegisterType((*Test2)(nil), "client.Test2")
	proto.RegisterType((*Test3)(nil), "client.Test3")
}

func init() { proto.RegisterFile("proto/client/msg.proto", fileDescriptor_e7504516c9b8cbfc) }

var fileDescriptor_e7504516c9b8cbfc = []byte{
	// 352 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0xcd, 0x4e, 0xf2, 0x40,
	0x14, 0xcd, 0x74, 0x98, 0x01, 0x2e, 0x3f, 0x09, 0x13, 0xc2, 0xd7, 0xe4, 0x5b, 0x48, 0x1a, 0x16,
	0xac, 0x24, 0xca, 0x1b, 0x28, 0x1b, 0x36, 0x6a, 0x46, 0x8c, 0x4b, 0x32, 0x9d, 0x0e, 0x0d, 0x41,
	0x8b, 0xa1, 0x4d, 0xed, 0x5b, 0xf9, 0x44, 0xbe, 0x8b, 0x99, 0x7b, 0xa9, 0x48, 0xdc, 0xd8, 0xdd,
	0x39, 0x67, 0xce, 0xb9, 0xf7, 0x9e, 0x14, 0x46, 0x6f, 0x87, 0x7d, 0xb1, 0x9f, 0xd9, 0x97, 0xad,
	0xcb, 0x8a, 0xd9, 0x6b, 0x9e, 0x5e, 0x22, 0xa1, 0x24, 0x31, 0xd1, 0x27, 0x83, 0xc6, 0xc3, 0x36,
	0x4b, 0xd5, 0x05, 0x74, 0x88, 0x5a, 0xe7, 0x2e, 0x4b, 0x42, 0x36, 0x66, 0x53, 0xa9, 0x81, 0xa8,
	0x47, 0x97, 0x25, 0xea, 0x3f, 0xb4, 0x53, 0x53, 0xb8, 0xf5, 0xc1, 0xd9, 0x32, 0x0c, 0x50, 0x6e,
	0x79, 0x42, 0x3b, 0x5b, 0x7e, 0x8b, 0xe8, 0xe5, 0x27, 0x11, 0x9d, 0xff, 0xa0, 0x99, 0xe6, 0xe4,
	0x6b, 0xa0, 0x24, 0xd3, 0x1c, 0x5d, 0x24, 0xa0, 0x47, 0xd4, 0x02, 0x3a, 0x22, 0xe8, 0x61, 0x5c,
	0x6c, 0xec, 0x6e, 0x7d, 0x70, 0x65, 0x28, 0x51, 0xee, 0x78, 0xf2, 0xc6, 0xd8, 0x9d, 0x76, 0xa5,
	0x9a, 0x40, 0xff, 0xf4, 0x06, 0x33, 0x9a, 0xf8, 0xa8, 0x5b, 0x3f, 0xf2, 0x49, 0xd1, 0x33, 0x88,
	0x95, 0xcb, 0x8b, 0x2b, 0xd5, 0x05, 0x66, 0xf0, 0x2a, 0xa1, 0x99, 0xf1, 0x28, 0xc6, 0x23, 0xda,
	0x9a, 0xc5, 0x1e, 0xd9, 0x90, 0x8f, 0xf9, 0x54, 0x6a, 0x66, 0x55, 0x1f, 0x82, 0xe5, 0x02, 0x37,
	0x15, 0x3a, 0x58, 0x2e, 0xd4, 0x10, 0xc4, 0xed, 0xfd, 0xd3, 0xdd, 0x0a, 0x77, 0x14, 0x9a, 0x40,
	0xf4, 0x4e, 0xc1, 0xd7, 0xa7, 0x60, 0xee, 0x83, 0x87, 0x20, 0xaa, 0xaa, 0x32, 0x26, 0x0c, 0xc6,
	0x7c, 0x3a, 0xd0, 0x04, 0xd4, 0x04, 0x7a, 0xd6, 0x5a, 0x5b, 0xd5, 0x1f, 0x56, 0xc4, 0xf5, 0x39,
	0xf9, 0xc7, 0xc1, 0x1f, 0x8c, 0x26, 0xcf, 0xd5, 0x08, 0xa4, 0xa1, 0x38, 0x86, 0x97, 0x1c, 0x91,
	0xf7, 0x95, 0x48, 0xfb, 0x03, 0x07, 0x9a, 0x00, 0xed, 0xc9, 0xcf, 0x0a, 0xa0, 0x51, 0x75, 0x01,
	0x34, 0x85, 0x59, 0x8f, 0x12, 0x6c, 0x5c, 0x68, 0x96, 0x78, 0xe4, 0xb0, 0x5a, 0xa1, 0x99, 0xf3,
	0x68, 0x13, 0xb6, 0xa8, 0xb8, 0xcd, 0x71, 0xe3, 0xf6, 0xef, 0x8d, 0xe1, 0xc7, 0xc6, 0xb1, 0xc4,
	0x5f, 0x6e, 0xfe, 0x15, 0x00, 0x00, 0xff, 0xff, 0xa5, 0xf2, 0x09, 0x4c, 0x8c, 0x02, 0x00, 0x00,
}
